apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fz1imisge-python 
  janus-idp.io/tekton: fz1imisge-python
  backstage.io/kubernetes-id: fz1imisge-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fz1imisge-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  