apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fz1imisge-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-6246513e29.8oy7.p3.openshiftapps.com/rhtap/rhtap-qe:c4c6883e94297e879525527b2f7b31f26b1952d6@sha256:a15aad9ded3d4fb16a1cf403dc352c05ed6e2569fca82bf19bb734be41a5d7e2
          name: container-image
