apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fz1imisge-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fz1imisge-python 
  name: fz1imisge-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fz1imisge-python 
